// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModDepends(arg1) {
	return window["go"]["parser"]["ScraperService"]["GetModDepends"](arg1);
}

export function GetModDetails(arg1) {
	return window["go"]["parser"]["ScraperService"]["GetModDetails"](arg1);
}

export function GetMods() {
	return window["go"]["parser"]["ScraperService"]["GetMods"]();
}

export function GetModsByPage(arg1, arg2) {
	return window["go"]["parser"]["ScraperService"]["GetModsByPage"](arg1, arg2);
}

export function GetSearchMods(arg1, arg2) {
	return window["go"]["parser"]["ScraperService"]["GetSearchMods"](arg1, arg2);
}
