// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parser} from '../models';

export function GetModDepends(arg1:Array<parser.ModDependency>):Promise<Array<parser.ModDependency>>;

export function GetModDetails(arg1:string):Promise<parser.MinecraftMod>;

export function GetMods():Promise<Array<parser.MinecraftMod>>;

export function GetModsByPage(arg1:number,arg2:any):Promise<Array<parser.MinecraftMod>>;

export function GetSearchMods(arg1:string,arg2:number):Promise<Array<parser.MinecraftMod>>;
