// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMinecraftModDetailsV1(arg1) {
  return window['go']['parser']['ScraperService']['GetMinecraftModDetailsV1'](arg1);
}

export function GetModDepends(arg1, arg2) {
  return window['go']['parser']['ScraperService']['GetModDepends'](arg1, arg2);
}

export function GetModDetails(arg1, arg2) {
  return window['go']['parser']['ScraperService']['GetModDetails'](arg1, arg2);
}

export function GetMods() {
  return window['go']['parser']['ScraperService']['GetMods']();
}

export function GetModsByPage(arg1, arg2) {
  return window['go']['parser']['ScraperService']['GetModsByPage'](arg1, arg2);
}

export function GetSearchMods(arg1, arg2) {
  return window['go']['parser']['ScraperService']['GetSearchMods'](arg1, arg2);
}

export function GetTextureByPage(arg1, arg2) {
  return window['go']['parser']['ScraperService']['GetTextureByPage'](arg1, arg2);
}
