// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LaunchMinecraft(arg1) {
  return window['go']['launcher']['LauncherService']['LaunchMinecraft'](arg1);
}

export function LaunchMinecraftD() {
  return window['go']['launcher']['LauncherService']['LaunchMinecraftD']();
}
