// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFileToMinecraftMods(arg1, arg2) {
  return window['go']['filetools']['FileService']['DownloadFileToMinecraftMods'](arg1, arg2);
}

export function DownloadsMods(arg1, arg2) {
  return window['go']['filetools']['FileService']['DownloadsMods'](arg1, arg2);
}

export function RemoveAllMods() {
  return window['go']['filetools']['FileService']['RemoveAllMods']();
}
