// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenExternalLink(arg1) {
	return window["go"]["main"]["App"]["OpenExternalLink"](arg1);
}

export function ShowInfoMessage(arg1, arg2) {
	return window["go"]["main"]["App"]["ShowInfoMessage"](arg1, arg2);
}
