// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parser} from '../models';

export function DownloadFileToMinecraftMods(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadsMods(arg1:Array<string>,arg2:Array<parser.DownloadInfo>):Promise<void>;
