// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSavedMod(arg1) {
  return window['go']['main']['FuncService']['DeleteSavedMod'](arg1);
}

export function GetSavedMods() {
  return window['go']['main']['FuncService']['GetSavedMods']();
}

export function GetYamlConfig(arg1) {
  return window['go']['main']['FuncService']['GetYamlConfig'](arg1);
}

export function RemoveFromYamlConfig(arg1, arg2) {
  return window['go']['main']['FuncService']['RemoveFromYamlConfig'](arg1, arg2);
}

export function SaveYamlModConfig(arg1, arg2) {
  return window['go']['main']['FuncService']['SaveYamlModConfig'](arg1, arg2);
}

export function SortByLoader(arg1, arg2) {
  return window['go']['main']['FuncService']['SortByLoader'](arg1, arg2);
}

export function SortByVersions(arg1, arg2) {
  return window['go']['main']['FuncService']['SortByVersions'](arg1, arg2);
}
