// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SortByLoader(arg1, arg2) {
  return window['go']['main']['FuncService']['SortByLoader'](arg1, arg2);
}

export function SortByVersions(arg1, arg2) {
  return window['go']['main']['FuncService']['SortByVersions'](arg1, arg2);
}
