// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parser} from '../models';

export function DeleteSavedMod(arg1:string):Promise<void>;

export function GetSavedMods():Promise<Array<string>>;

export function SortByLoader(arg1:Array<parser.MinecraftMod>,arg2:string):Promise<Array<parser.MinecraftMod>>;

export function SortByVersions(arg1:Array<parser.MinecraftMod>,arg2:string):Promise<Array<parser.MinecraftMod>>;
