// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SortByLoader(arg1:Array<main.MinecraftMod>,arg2:string):Promise<Array<main.MinecraftMod>>;

export function SortByVersions(arg1:Array<main.MinecraftMod>,arg2:string):Promise<Array<main.MinecraftMod>>;
