// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetModDepends(arg1:Array<main.ModDependency>):Promise<Array<main.ModDependency>>;

export function GetModDetails(arg1:string):Promise<main.MinecraftMod>;

export function GetMods():Promise<Array<main.MinecraftMod>>;

export function GetModsByPage(arg1:number,arg2:any):Promise<Array<main.MinecraftMod>>;

export function GetSearchMods(arg1:string,arg2:number):Promise<Array<main.MinecraftMod>>;
