// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModDetails(arg1) {
  return window['go']['main']['ScraperService']['GetModDetails'](arg1);
}

export function GetMods() {
  return window['go']['main']['ScraperService']['GetMods']();
}

export function GetModsByPage(arg1) {
  return window['go']['main']['ScraperService']['GetModsByPage'](arg1);
}

export function GetSearchMods(arg1) {
  return window['go']['main']['ScraperService']['GetSearchMods'](arg1);
}
